package basic.language.behavior;

/*Generated by MPS */

import jetbrains.mps.core.aspects.behaviour.BaseBehaviorAspectDescriptor;
import jetbrains.mps.core.aspects.behaviour.api.BHDescriptor;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public final class BehaviorAspectDescriptor extends BaseBehaviorAspectDescriptor {
  private final BHDescriptor myBStatementContainer__BehaviorDescriptor = new BStatementContainer__BehaviorDescriptor();
  private final BHDescriptor myBIfStatement__BehaviorDescriptor = new BIfStatement__BehaviorDescriptor();
  private final BHDescriptor myBWorkbook__BehaviorDescriptor = new BWorkbook__BehaviorDescriptor();
  private final BHDescriptor myBPlusExpression__BehaviorDescriptor = new BPlusExpression__BehaviorDescriptor();
  private final BHDescriptor myBMinusExpression__BehaviorDescriptor = new BMinusExpression__BehaviorDescriptor();
  private final BHDescriptor myBMulExpression__BehaviorDescriptor = new BMulExpression__BehaviorDescriptor();
  private final BHDescriptor myBBinaryExpression__BehaviorDescriptor = new BBinaryExpression__BehaviorDescriptor();

  public BehaviorAspectDescriptor() {
  }

  @Nullable
  public BHDescriptor getDescriptor(@NotNull SAbstractConcept concept) {
    SAbstractConcept cncpt = concept;
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return myBBinaryExpression__BehaviorDescriptor;
      case 1:
        return myBIfStatement__BehaviorDescriptor;
      case 2:
        return myBMinusExpression__BehaviorDescriptor;
      case 3:
        return myBMulExpression__BehaviorDescriptor;
      case 4:
        return myBPlusExpression__BehaviorDescriptor;
      case 5:
        return myBStatementContainer__BehaviorDescriptor;
      case 6:
        return myBWorkbook__BehaviorDescriptor;
      default:
    }
    return null;
  }
  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0xdf20d2ac476c4ef8L, 0x8b3f4802becda85fL, 0x5d451e22fa44bdb5L), MetaIdFactory.conceptId(0xdf20d2ac476c4ef8L, 0x8b3f4802becda85fL, 0xd51973b09d73161L), MetaIdFactory.conceptId(0xdf20d2ac476c4ef8L, 0x8b3f4802becda85fL, 0x5d451e22fa447d47L), MetaIdFactory.conceptId(0xdf20d2ac476c4ef8L, 0x8b3f4802becda85fL, 0x5d451e22fa4499d6L), MetaIdFactory.conceptId(0xdf20d2ac476c4ef8L, 0x8b3f4802becda85fL, 0x5d451e22fa4443b7L), MetaIdFactory.conceptId(0xdf20d2ac476c4ef8L, 0x8b3f4802becda85fL, 0xd51973b09d195ddL), MetaIdFactory.conceptId(0xdf20d2ac476c4ef8L, 0x8b3f4802becda85fL, 0x5d451e22fa438438L)).seal();
}
